# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import neurostore_sdk
from neurostore_sdk.models.studyset_return import StudysetReturn  # noqa: E501
from neurostore_sdk.rest import ApiException

class TestStudysetReturn(unittest.TestCase):
    """StudysetReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test StudysetReturn
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StudysetReturn`
        """
        model = neurostore_sdk.models.studyset_return.StudysetReturn()  # noqa: E501
        if include_optional :
            return StudysetReturn(
                name = 'Examination of want versus need', 
                description = 'A collection of studies that include tasks x, y, and z, for the purpose of teasing apart concepts a and b.', 
                publication = 'Journal of Open Results', 
                doi = 'digital object identifier of the studyset', 
                pmid = '35998675', 
                created_at = '2021-01-16T20:50:38.009318Z', 
                updated_at = '', 
                id = '38jobTomPDqt', 
                public = True, 
                user = '', 
                username = '', 
                source = '', 
                source_id = '', 
                source_updated_at = '', 
                studies = None, 
                level = 'group'
            )
        else :
            return StudysetReturn(
        )
        """

    def testStudysetReturn(self):
        """Test StudysetReturn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
