# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.models.studyset_request import StudysetRequest

class TestStudysetRequest(unittest.TestCase):
    """StudysetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StudysetRequest:
        """Test StudysetRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StudysetRequest`
        """
        model = StudysetRequest()
        if include_optional:
            return StudysetRequest(
                name = 'Examination of want versus need',
                description = 'A collection of studies that include tasks x, y, and z, for the purpose of teasing apart concepts a and b.',
                publication = 'Journal of Open Results',
                doi = 'digital object identifier of the studyset',
                pmid = '35998675',
                studies = [
                    None
                    ],
                id = '38jobTomPDqt',
                public = True,
                level = 'group'
            )
        else:
            return StudysetRequest(
        )
        """

    def testStudysetRequest(self):
        """Test StudysetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
