"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.writeable_resource_attributes import WriteableResourceAttributes


class TestWriteableResourceAttributes(unittest.TestCase):
    """WriteableResourceAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWriteableResourceAttributes(self):
        """Test WriteableResourceAttributes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WriteableResourceAttributes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
