# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.2
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.models.neurostore_studyset_releases_get200_response import NeurostoreStudysetReleasesGet200Response

class TestNeurostoreStudysetReleasesGet200Response(unittest.TestCase):
    """NeurostoreStudysetReleasesGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NeurostoreStudysetReleasesGet200Response:
        """Test NeurostoreStudysetReleasesGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NeurostoreStudysetReleasesGet200Response`
        """
        model = NeurostoreStudysetReleasesGet200Response()
        if include_optional:
            return NeurostoreStudysetReleasesGet200Response(
                metadata = neurostore_sdk.models._neurostore_studyset_releases__get_200_response_metadata._neurostore_studyset_releases__get_200_response_metadata(
                    total_count = 56, ),
                results = [
                    None
                    ]
            )
        else:
            return NeurostoreStudysetReleasesGet200Response(
        )
        """

    def testNeurostoreStudysetReleasesGet200Response(self):
        """Test NeurostoreStudysetReleasesGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
