# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.models.json_ld_context import JsonLdContext

class TestJsonLdContext(unittest.TestCase):
    """JsonLdContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonLdContext:
        """Test JsonLdContext
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonLdContext`
        """
        model = JsonLdContext()
        if include_optional:
            return JsonLdContext(
                vocab = ''
            )
        else:
            return JsonLdContext(
        )
        """

    def testJsonLdContext(self):
        """Test JsonLdContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
