# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.models.study_request_relationships_analyses import StudyRequestRelationshipsAnalyses

class TestStudyRequestRelationshipsAnalyses(unittest.TestCase):
    """StudyRequestRelationshipsAnalyses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StudyRequestRelationshipsAnalyses:
        """Test StudyRequestRelationshipsAnalyses
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StudyRequestRelationshipsAnalyses`
        """
        model = StudyRequestRelationshipsAnalyses()
        if include_optional:
            return StudyRequestRelationshipsAnalyses(
            )
        else:
            return StudyRequestRelationshipsAnalyses(
        )
        """

    def testStudyRequestRelationshipsAnalyses(self):
        """Test StudyRequestRelationshipsAnalyses"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
