# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import neurostore_sdk
from neurostore_sdk.models.base_studies_post_request import BaseStudiesPostRequest  # noqa: E501
from neurostore_sdk.rest import ApiException

class TestBaseStudiesPostRequest(unittest.TestCase):
    """BaseStudiesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BaseStudiesPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseStudiesPostRequest`
        """
        model = neurostore_sdk.models.base_studies_post_request.BaseStudiesPostRequest()  # noqa: E501
        if include_optional :
            return BaseStudiesPostRequest(
                metadata = neurostore_sdk.models.metadata.metadata(), 
                versions = None, 
                name = '', 
                description = '', 
                publication = '', 
                doi = '', 
                pmid = '', 
                authors = '', 
                year = 56, 
                level = '', 
                pmcid = ''
            )
        else :
            return BaseStudiesPostRequest(
        )
        """

    def testBaseStudiesPostRequest(self):
        """Test BaseStudiesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
