# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.api.studysets_api import StudysetsApi


class TestStudysetsApi(unittest.TestCase):
    """StudysetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StudysetsApi()

    def tearDown(self) -> None:
        pass

    def test_studysets_get(self) -> None:
        """Test case for studysets_get

        GET a list of studysets
        """
        pass

    def test_studysets_id_delete(self) -> None:
        """Test case for studysets_id_delete

        DELETE a studyset
        """
        pass

    def test_studysets_id_get(self) -> None:
        """Test case for studysets_id_get

        GET a studyset
        """
        pass

    def test_studysets_id_put(self) -> None:
        """Test case for studysets_id_put

        PUT/update a studyset
        """
        pass

    def test_studysets_post(self) -> None:
        """Test case for studysets_post

        POST/create a studyset
        """
        pass


if __name__ == '__main__':
    unittest.main()
