"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.note_collection_request import NoteCollectionRequest
globals()['NoteCollectionRequest'] = NoteCollectionRequest
from neurostore_sdk.model.annotation_request_relationships import AnnotationRequestRelationships


class TestAnnotationRequestRelationships(unittest.TestCase):
    """AnnotationRequestRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationRequestRelationships(self):
        """Test AnnotationRequestRelationships"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationRequestRelationships()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
