# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import neurostore_sdk
from neurostore_sdk.models.studysets_id_put422_response import StudysetsIdPut422Response  # noqa: E501
from neurostore_sdk.rest import ApiException

class TestStudysetsIdPut422Response(unittest.TestCase):
    """StudysetsIdPut422Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test StudysetsIdPut422Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StudysetsIdPut422Response`
        """
        model = neurostore_sdk.models.studysets_id_put422_response.StudysetsIdPut422Response()  # noqa: E501
        if include_optional :
            return StudysetsIdPut422Response(
                detail = 'The request was well-formed but was unable to be followed due to semantic errors.', 
                status = 56, 
                title = 'Unprocessable Entity', 
                type = 'about:blank'
            )
        else :
            return StudysetsIdPut422Response(
        )
        """

    def testStudysetsIdPut422Response(self):
        """Test StudysetsIdPut422Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
