"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.analysis_request import AnalysisRequest
from neurostore_sdk.model.study_base import StudyBase
from neurostore_sdk.model.study_request_relationships import StudyRequestRelationships
from neurostore_sdk.model.writeable_resource_attributes import WriteableResourceAttributes
globals()['AnalysisRequest'] = AnalysisRequest
globals()['StudyBase'] = StudyBase
globals()['StudyRequestRelationships'] = StudyRequestRelationships
globals()['WriteableResourceAttributes'] = WriteableResourceAttributes
from neurostore_sdk.model.study_request import StudyRequest


class TestStudyRequest(unittest.TestCase):
    """StudyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudyRequest(self):
        """Test StudyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
