# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.1
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.models.annotation_return_one_of import AnnotationReturnOneOf

class TestAnnotationReturnOneOf(unittest.TestCase):
    """AnnotationReturnOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnnotationReturnOneOf:
        """Test AnnotationReturnOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnnotationReturnOneOf`
        """
        model = AnnotationReturnOneOf()
        if include_optional:
            return AnnotationReturnOneOf(
                name = 'Examination of left versus right finger tapping',
                description = 'This annotation tracks whether the analysis of interest for all included studies are left handed/right handed, or bimanual taps.',
                metadata = neurostore_sdk.models.metadata.metadata(),
                note_keys = {include=boolean},
                created_at = '2021-01-16T20:50:38.009318Z',
                updated_at = '',
                id = '38jobTomPDqt',
                public = True,
                user = '',
                username = '',
                source = '',
                source_id = '',
                source_updated_at = '',
                notes = None,
                studyset = ''
            )
        else:
            return AnnotationReturnOneOf(
        )
        """

    def testAnnotationReturnOneOf(self):
        """Test AnnotationReturnOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
