# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_users_get(self) -> None:
        """Test case for users_get

        Your GET endpoint
        """
        pass

    def test_users_id_get(self) -> None:
        """Test case for users_id_get

        Individual User Profile
        """
        pass

    def test_users_id_put(self) -> None:
        """Test case for users_id_put

        Update Individual Profile
        """
        pass

    def test_users_post(self) -> None:
        """Test case for users_post

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
