# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.models.error_detail import ErrorDetail

class TestErrorDetail(unittest.TestCase):
    """ErrorDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorDetail:
        """Test ErrorDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorDetail`
        """
        model = ErrorDetail()
        if include_optional:
            return ErrorDetail(
                var_field = 'source',
                code = 'INVALID_VALUE',
                message = 'invalid source, choose from: 'neurostore'',
                context = { }
            )
        else:
            return ErrorDetail(
                code = 'INVALID_VALUE',
                message = 'invalid source, choose from: 'neurostore'',
        )
        """

    def testErrorDetail(self):
        """Test ErrorDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
