"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.study_return import StudyReturn
globals()['StudyReturn'] = StudyReturn
from neurostore_sdk.model.studyset_return_all_of import StudysetReturnAllOf


class TestStudysetReturnAllOf(unittest.TestCase):
    """StudysetReturnAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudysetReturnAllOf(self):
        """Test StudysetReturnAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudysetReturnAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
