"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.analysis_request import AnalysisRequest
globals()['AnalysisRequest'] = AnalysisRequest
from neurostore_sdk.model.study_request_relationships import StudyRequestRelationships


class TestStudyRequestRelationships(unittest.TestCase):
    """StudyRequestRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudyRequestRelationships(self):
        """Test StudyRequestRelationships"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudyRequestRelationships()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
