# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import neurostore_sdk
from neurostore_sdk.models.point_value import PointValue  # noqa: E501
from neurostore_sdk.rest import ApiException

class TestPointValue(unittest.TestCase):
    """PointValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PointValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PointValue`
        """
        model = neurostore_sdk.models.point_value.PointValue()  # noqa: E501
        if include_optional :
            return PointValue(
                kind = '', 
                value = 1.337
            )
        else :
            return PointValue(
        )
        """

    def testPointValue(self):
        """Test PointValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
