# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.2
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.models.studyset_request_relationships_studies_inner import StudysetRequestRelationshipsStudiesInner

class TestStudysetRequestRelationshipsStudiesInner(unittest.TestCase):
    """StudysetRequestRelationshipsStudiesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StudysetRequestRelationshipsStudiesInner:
        """Test StudysetRequestRelationshipsStudiesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StudysetRequestRelationshipsStudiesInner`
        """
        model = StudysetRequestRelationshipsStudiesInner()
        if include_optional:
            return StudysetRequestRelationshipsStudiesInner(
                id = '38jobTomPDqt',
                curation_stub_uuid = '',
                doi = '10.1016/S0926-6410(97)00020-7',
                name = 'Functional magnetic resonance imaging of category-specific cortical activation: evidence for semantic maps.',
                metadata = neurostore_sdk.models.metadata.metadata(),
                description = 'This is my very scientific abstract.',
                publication = 'Journal of Super Important Science.',
                pmid = '35998675',
                authors = 'Strange, M.',
                year = 1991,
                analyses = None,
                public = True,
                pmcid = ''
            )
        else:
            return StudysetRequestRelationshipsStudiesInner(
                id = '38jobTomPDqt',
        )
        """

    def testStudysetRequestRelationshipsStudiesInner(self):
        """Test StudysetRequestRelationshipsStudiesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
