# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.2
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.models.neurostore_studyset_releases_get200_response_metadata import NeurostoreStudysetReleasesGet200ResponseMetadata

class TestNeurostoreStudysetReleasesGet200ResponseMetadata(unittest.TestCase):
    """NeurostoreStudysetReleasesGet200ResponseMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NeurostoreStudysetReleasesGet200ResponseMetadata:
        """Test NeurostoreStudysetReleasesGet200ResponseMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NeurostoreStudysetReleasesGet200ResponseMetadata`
        """
        model = NeurostoreStudysetReleasesGet200ResponseMetadata()
        if include_optional:
            return NeurostoreStudysetReleasesGet200ResponseMetadata(
                total_count = 56
            )
        else:
            return NeurostoreStudysetReleasesGet200ResponseMetadata(
        )
        """

    def testNeurostoreStudysetReleasesGet200ResponseMetadata(self):
        """Test NeurostoreStudysetReleasesGet200ResponseMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
