"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.note_collection_base import NoteCollectionBase
from neurostore_sdk.model.note_collection_return_all_of import NoteCollectionReturnAllOf
globals()['NoteCollectionBase'] = NoteCollectionBase
globals()['NoteCollectionReturnAllOf'] = NoteCollectionReturnAllOf
from neurostore_sdk.model.note_collection_return import NoteCollectionReturn


class TestNoteCollectionReturn(unittest.TestCase):
    """NoteCollectionReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNoteCollectionReturn(self):
        """Test NoteCollectionReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NoteCollectionReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
