# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.api.pipeline_runs_api import PipelineRunsApi


class TestPipelineRunsApi(unittest.TestCase):
    """PipelineRunsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PipelineRunsApi()

    def tearDown(self) -> None:
        pass

    def test_pipeline_runs_get(self) -> None:
        """Test case for pipeline_runs_get

        GET a list of pipeline runs
        """
        pass

    def test_pipeline_runs_pipeline_run_id_delete(self) -> None:
        """Test case for pipeline_runs_pipeline_run_id_delete

        DELETE a pipeline run by ID
        """
        pass

    def test_pipeline_runs_pipeline_run_id_get(self) -> None:
        """Test case for pipeline_runs_pipeline_run_id_get

        GET a pipeline run by ID
        """
        pass

    def test_pipeline_runs_pipeline_run_id_put(self) -> None:
        """Test case for pipeline_runs_pipeline_run_id_put

        PUT/update a pipeline run by ID
        """
        pass

    def test_pipeline_runs_post(self) -> None:
        """Test case for pipeline_runs_post

        POST/create a pipeline run
        """
        pass


if __name__ == '__main__':
    unittest.main()
