# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import neurostore_sdk
from neurostore_sdk.api.default_api import DefaultApi  # noqa: E501
from neurostore_sdk.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = neurostore_sdk.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_base_studies_get(self):
        """Test case for base_studies_get

          # noqa: E501
        """
        pass

    def test_base_studies_id_get(self):
        """Test case for base_studies_id_get

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_base_studies_id_put(self):
        """Test case for base_studies_id_put

          # noqa: E501
        """
        pass

    def test_base_studies_post(self):
        """Test case for base_studies_post

          # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
