# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import neurostore_sdk
from neurostore_sdk.api.images_api import ImagesApi  # noqa: E501
from neurostore_sdk.rest import ApiException


class TestImagesApi(unittest.TestCase):
    """ImagesApi unit test stubs"""

    def setUp(self):
        self.api = neurostore_sdk.api.images_api.ImagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_images_get(self):
        """Test case for images_get

        GET a list of images  # noqa: E501
        """
        pass

    def test_images_id_delete(self):
        """Test case for images_id_delete

        DELETE an image  # noqa: E501
        """
        pass

    def test_images_id_get(self):
        """Test case for images_id_get

        GET an image  # noqa: E501
        """
        pass

    def test_images_id_put(self):
        """Test case for images_id_put

        PUT/update an image  # noqa: E501
        """
        pass

    def test_images_post(self):
        """Test case for images_post

        POST/create an image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
