"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.point_common import PointCommon


class TestPointCommon(unittest.TestCase):
    """PointCommon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointCommon(self):
        """Test PointCommon"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PointCommon()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
