# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.models.image_base import ImageBase

class TestImageBase(unittest.TestCase):
    """ImageBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageBase:
        """Test ImageBase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageBase`
        """
        model = ImageBase()
        if include_optional:
            return ImageBase(
                metadata = neurostore_sdk.models.metadata.metadata(),
                url = 'https://neurovault.org/media/images/4778/Positive_RPEs_zstat.nii.gz',
                filename = 'Positive_RPEs_zstat.nii.gz',
                space = 'MNI152NLin2009aAsym',
                value_type = 'Z',
                add_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ImageBase(
        )
        """

    def testImageBase(self):
        """Test ImageBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
