"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.study_request import StudyRequest
from neurostore_sdk.model.studyset_base import StudysetBase
from neurostore_sdk.model.studyset_request_relationships import StudysetRequestRelationships
from neurostore_sdk.model.writeable_resource_attributes import WriteableResourceAttributes
globals()['StudyRequest'] = StudyRequest
globals()['StudysetBase'] = StudysetBase
globals()['StudysetRequestRelationships'] = StudysetRequestRelationships
globals()['WriteableResourceAttributes'] = WriteableResourceAttributes
from neurostore_sdk.model.studyset_request import StudysetRequest


class TestStudysetRequest(unittest.TestCase):
    """StudysetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudysetRequest(self):
        """Test StudysetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudysetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
