# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.2
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.models.image_detail import ImageDetail

class TestImageDetail(unittest.TestCase):
    """ImageDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageDetail:
        """Test ImageDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageDetail`
        """
        model = ImageDetail()
        if include_optional:
            return ImageDetail(
                value_summary = neurostore_sdk.models.image_value_summary.image-value-summary(
                    status = '', 
                    error = '', 
                    summarizer_version = 56, 
                    computed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    source_sha256 = '', 
                    source_bytes = 56, 
                    n_voxels = 56, 
                    n_values = 56, 
                    fraction_nan = 1.337, 
                    fraction_zero = 1.337, 
                    fraction_negative = 1.337, 
                    min = 1.337, 
                    max = 1.337, 
                    mean = 1.337, 
                    std = 1.337, 
                    percentiles = {
                        'key' : 1.337
                        }, 
                    histogram = neurostore_sdk.models.image_value_summary_histogram.image_value_summary_histogram(
                        min = 1.337, 
                        max = 1.337, 
                        bin_width = 1.337, 
                        counts = [
                            56
                            ], 
                        underflow = 56, 
                        overflow = 56, ), )
            )
        else:
            return ImageDetail(
        )
        """

    def testImageDetail(self):
        """Test ImageDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
