"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.study_return import StudyReturn
from neurostore_sdk.model.studyset_base import StudysetBase
from neurostore_sdk.model.studyset_relationships import StudysetRelationships
globals()['StudyReturn'] = StudyReturn
globals()['StudysetBase'] = StudysetBase
globals()['StudysetRelationships'] = StudysetRelationships
from neurostore_sdk.model.studyset_request import StudysetRequest


class TestStudysetRequest(unittest.TestCase):
    """StudysetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudysetRequest(self):
        """Test StudysetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudysetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
