# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.api.images_api import ImagesApi


class TestImagesApi(unittest.TestCase):
    """ImagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImagesApi()

    def tearDown(self) -> None:
        pass

    def test_images_get(self) -> None:
        """Test case for images_get

        GET a list of images
        """
        pass

    def test_images_id_delete(self) -> None:
        """Test case for images_id_delete

        DELETE an image
        """
        pass

    def test_images_id_get(self) -> None:
        """Test case for images_id_get

        GET an image
        """
        pass

    def test_images_id_put(self) -> None:
        """Test case for images_id_put

        PUT/update an image
        """
        pass

    def test_images_post(self) -> None:
        """Test case for images_post

        POST/create an image
        """
        pass


if __name__ == '__main__':
    unittest.main()
