"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.note_collection import NoteCollection
from neurostore_sdk.model.studyset import Studyset
globals()['NoteCollection'] = NoteCollection
globals()['Studyset'] = Studyset
from neurostore_sdk.model.annotation_relationships import AnnotationRelationships


class TestAnnotationRelationships(unittest.TestCase):
    """AnnotationRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationRelationships(self):
        """Test AnnotationRelationships"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationRelationships()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
