"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.condition_base import ConditionBase
from neurostore_sdk.model.writeable_resource_attributes import WriteableResourceAttributes
globals()['ConditionBase'] = ConditionBase
globals()['WriteableResourceAttributes'] = WriteableResourceAttributes
from neurostore_sdk.model.condition_request import ConditionRequest


class TestConditionRequest(unittest.TestCase):
    """ConditionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConditionRequest(self):
        """Test ConditionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConditionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
