# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import neurostore_sdk
from neurostore_sdk.api.pipelines_api import PipelinesApi  # noqa: E501
from neurostore_sdk.rest import ApiException


class TestPipelinesApi(unittest.TestCase):
    """PipelinesApi unit test stubs"""

    def setUp(self):
        self.api = neurostore_sdk.api.pipelines_api.PipelinesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pipelines_get(self):
        """Test case for pipelines_get

        GET a list of pipelines  # noqa: E501
        """
        pass

    def test_pipelines_id_delete(self):
        """Test case for pipelines_id_delete

        DELETE a pipeline by ID  # noqa: E501
        """
        pass

    def test_pipelines_id_get(self):
        """Test case for pipelines_id_get

        GET a pipeline by ID  # noqa: E501
        """
        pass

    def test_pipelines_id_put(self):
        """Test case for pipelines_id_put

        PUT/update a pipeline by ID  # noqa: E501
        """
        pass

    def test_pipelines_post(self):
        """Test case for pipelines_post

        POST/create a pipeline  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
