"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.note_collection_base import NoteCollectionBase
from neurostore_sdk.model.writeable_resource_attributes import WriteableResourceAttributes
globals()['NoteCollectionBase'] = NoteCollectionBase
globals()['WriteableResourceAttributes'] = WriteableResourceAttributes
from neurostore_sdk.model.note_collection_request import NoteCollectionRequest


class TestNoteCollectionRequest(unittest.TestCase):
    """NoteCollectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNoteCollectionRequest(self):
        """Test NoteCollectionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NoteCollectionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
