"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.entity_all_of import EntityAllOf


class TestEntityAllOf(unittest.TestCase):
    """EntityAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityAllOf(self):
        """Test EntityAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
