# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurostore_sdk.models.studyset_request_relationships_studies_inner_one_of import StudysetRequestRelationshipsStudiesInnerOneOf

class TestStudysetRequestRelationshipsStudiesInnerOneOf(unittest.TestCase):
    """StudysetRequestRelationshipsStudiesInnerOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StudysetRequestRelationshipsStudiesInnerOneOf:
        """Test StudysetRequestRelationshipsStudiesInnerOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StudysetRequestRelationshipsStudiesInnerOneOf`
        """
        model = StudysetRequestRelationshipsStudiesInnerOneOf()
        if include_optional:
            return StudysetRequestRelationshipsStudiesInnerOneOf(
                id = '',
                curation_stub_uuid = ''
            )
        else:
            return StudysetRequestRelationshipsStudiesInnerOneOf(
                id = '',
        )
        """

    def testStudysetRequestRelationshipsStudiesInnerOneOf(self):
        """Test StudysetRequestRelationshipsStudiesInnerOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
