# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""

from neurostore_sdk.paths.conditions_.get import ConditionsGet
from neurostore_sdk.paths.conditions_id.delete import ConditionsIdDelete
from neurostore_sdk.paths.conditions_id.get import ConditionsIdGet
from neurostore_sdk.paths.conditions_id.put import ConditionsIdPut
from neurostore_sdk.paths.conditions_.post import ConditionsPost


class ConditionsApi(
    ConditionsGet,
    ConditionsIdDelete,
    ConditionsIdGet,
    ConditionsIdPut,
    ConditionsPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
