# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""

from neurostore_sdk.paths.analyses_.get import AnalysesGet
from neurostore_sdk.paths.analyses_id.delete import AnalysesIdDelete
from neurostore_sdk.paths.analyses_id.get import AnalysesIdGet
from neurostore_sdk.paths.analyses_id.put import AnalysesIdPut
from neurostore_sdk.paths.analyses_.post import AnalysesPost
from neurostore_sdk.paths.annotations_.get import AnnotationsGet
from neurostore_sdk.paths.annotations_id.delete import AnnotationsIdDelete
from neurostore_sdk.paths.annotations_id.get import AnnotationsIdGet
from neurostore_sdk.paths.annotations_id.put import AnnotationsIdPut
from neurostore_sdk.paths.annotations_.post import AnnotationsPost
from neurostore_sdk.paths.conditions_.get import ConditionsGet
from neurostore_sdk.paths.conditions_id.delete import ConditionsIdDelete
from neurostore_sdk.paths.conditions_id.get import ConditionsIdGet
from neurostore_sdk.paths.conditions_id.put import ConditionsIdPut
from neurostore_sdk.paths.conditions_.post import ConditionsPost
from neurostore_sdk.paths.images_.get import ImagesGet
from neurostore_sdk.paths.images_id.delete import ImagesIdDelete
from neurostore_sdk.paths.images_id.get import ImagesIdGet
from neurostore_sdk.paths.images_id.put import ImagesIdPut
from neurostore_sdk.paths.images_.post import ImagesPost
from neurostore_sdk.paths.points_.get import PointsGet
from neurostore_sdk.paths.points_id.delete import PointsIdDelete
from neurostore_sdk.paths.points_id.get import PointsIdGet
from neurostore_sdk.paths.points_id.put import PointsIdPut
from neurostore_sdk.paths.points_.post import PointsPost
from neurostore_sdk.paths.studies_.get import StudiesGet
from neurostore_sdk.paths.studies_id.delete import StudiesIdDelete
from neurostore_sdk.paths.studies_id.get import StudiesIdGet
from neurostore_sdk.paths.studies_id.put import StudiesIdPut
from neurostore_sdk.paths.studies_.post import StudiesPost
from neurostore_sdk.paths.studysets_id.delete import StudysetsIdDelete
from neurostore_sdk.paths.studysets_id.get import StudysetsIdGet
from neurostore_sdk.paths.studysets_id.put import StudysetsIdPut
from neurostore_sdk.paths.studysets_.post import StudysetsPost


class StoreApi(
    AnalysesGet,
    AnalysesIdDelete,
    AnalysesIdGet,
    AnalysesIdPut,
    AnalysesPost,
    AnnotationsGet,
    AnnotationsIdDelete,
    AnnotationsIdGet,
    AnnotationsIdPut,
    AnnotationsPost,
    ConditionsGet,
    ConditionsIdDelete,
    ConditionsIdGet,
    ConditionsIdPut,
    ConditionsPost,
    ImagesGet,
    ImagesIdDelete,
    ImagesIdGet,
    ImagesIdPut,
    ImagesPost,
    PointsGet,
    PointsIdDelete,
    PointsIdGet,
    PointsIdPut,
    PointsPost,
    StudiesGet,
    StudiesIdDelete,
    StudiesIdGet,
    StudiesIdPut,
    StudiesPost,
    StudysetsIdDelete,
    StudysetsIdGet,
    StudysetsIdPut,
    StudysetsPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
