# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class Clone(BaseModel):
    """
    Clone
    """
    source: Optional[StrictStr] = None
    source_id: Optional[StrictStr] = None
    source_updated_at: Optional[StrictStr] = None
    __properties = ["source", "source_id", "source_updated_at"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Clone:
        """Create an instance of Clone from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "source_updated_at",
                          },
                          exclude_none=True)
        # set to None if source (nullable) is None
        # and __fields_set__ contains the field
        if self.source is None and "source" in self.__fields_set__:
            _dict['source'] = None

        # set to None if source_id (nullable) is None
        # and __fields_set__ contains the field
        if self.source_id is None and "source_id" in self.__fields_set__:
            _dict['source_id'] = None

        # set to None if source_updated_at (nullable) is None
        # and __fields_set__ contains the field
        if self.source_updated_at is None and "source_updated_at" in self.__fields_set__:
            _dict['source_updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Clone:
        """Create an instance of Clone from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Clone.parse_obj(obj)

        _obj = Clone.parse_obj({
            "source": obj.get("source"),
            "source_id": obj.get("source_id"),
            "source_updated_at": obj.get("source_updated_at")
        })
        return _obj

