# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class Entity(BaseModel):
    """
    WARNING: not currently used. descriptor of level of analysis for a particular image/point (run, session, subject, group, meta)
    """
    label: Optional[StrictStr] = None
    level: Optional[StrictStr] = None
    analysis: Optional[StrictStr] = None
    __properties = ["label", "level", "analysis"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Entity:
        """Create an instance of Entity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if label (nullable) is None
        # and __fields_set__ contains the field
        if self.label is None and "label" in self.__fields_set__:
            _dict['label'] = None

        # set to None if level (nullable) is None
        # and __fields_set__ contains the field
        if self.level is None and "level" in self.__fields_set__:
            _dict['level'] = None

        # set to None if analysis (nullable) is None
        # and __fields_set__ contains the field
        if self.analysis is None and "analysis" in self.__fields_set__:
            _dict['analysis'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Entity:
        """Create an instance of Entity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Entity.parse_obj(obj)

        _obj = Entity.parse_obj({
            "label": obj.get("label"),
            "level": obj.get("level"),
            "analysis": obj.get("analysis")
        })
        return _obj

