# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field

class NoteCollectionBase(BaseModel):
    """
    NoteCollectionBase
    """
    note: Optional[Dict[str, Any]] = Field(None, description="The note will contain all note_keys as keys and have a value of either null or the value type specified in note_keys.")
    __properties = ["note"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NoteCollectionBase:
        """Create an instance of NoteCollectionBase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if note (nullable) is None
        # and __fields_set__ contains the field
        if self.note is None and "note" in self.__fields_set__:
            _dict['note'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NoteCollectionBase:
        """Create an instance of NoteCollectionBase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NoteCollectionBase.parse_obj(obj)

        _obj = NoteCollectionBase.parse_obj({
            "note": obj.get("note")
        })
        return _obj

