# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from neurostore_sdk.models.entity import Entity
from neurostore_sdk.models.point_relationships_values import PointRelationshipsValues
from typing import Optional, Set
from typing_extensions import Self

class PointRequest(BaseModel):
    """
    PointRequest
    """ # noqa: E501
    coordinates: Optional[Annotated[List[Union[StrictFloat, StrictInt]], Field(min_length=3, max_length=3)]] = Field(default=None, description="Location of the significant coordinate in three dimensional space.")
    space: Optional[StrictStr] = Field(default=None, description="Template space used to determine coordinate Examples include TAL or MNI.")
    kind: Optional[StrictStr] = Field(default=None, description="Method of how point was derived (e.g., center of mass)")
    label_id: Optional[StrictStr] = Field(default=None, description="If the point is associated with an image, this is the value the point takes in that image.")
    image: Optional[StrictStr] = None
    values: Optional[PointRelationshipsValues] = None
    x: Optional[Union[StrictFloat, StrictInt]] = None
    y: Optional[Union[StrictFloat, StrictInt]] = None
    z: Optional[Union[StrictFloat, StrictInt]] = None
    entities: Optional[List[Entity]] = None
    id: Optional[Annotated[str, Field(min_length=12, strict=True, max_length=30)]] = Field(default=None, description="short UUID specifying the location of this resource")
    public: Optional[StrictBool] = Field(default=True, description="whether the resource is listed in public searches or not")
    analysis: Optional[StrictStr] = None
    cluster_size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="size of the cluster in cubic millimeters")
    subpeak: Optional[StrictBool] = Field(default=None, description="whether the reported peak is the max-peak statistic or a sub-maxmimal peak.")
    deactivation: Optional[StrictBool] = Field(default=None, description="wheather the coordinate represents an decrease in activation relative to a baseline")
    order: Optional[StrictInt] = Field(default=None, description="determines the row to display the coordinate")
    __properties: ClassVar[List[str]] = ["coordinates", "space", "kind", "label_id", "image", "values", "x", "y", "z", "entities", "id", "public", "analysis", "cluster_size", "subpeak", "deactivation", "order"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PointRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of values
        if self.values:
            _dict['values'] = self.values.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in entities (list)
        _items = []
        if self.entities:
            for _item_entities in self.entities:
                if _item_entities:
                    _items.append(_item_entities.to_dict())
            _dict['entities'] = _items
        # set to None if space (nullable) is None
        # and model_fields_set contains the field
        if self.space is None and "space" in self.model_fields_set:
            _dict['space'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        # set to None if label_id (nullable) is None
        # and model_fields_set contains the field
        if self.label_id is None and "label_id" in self.model_fields_set:
            _dict['label_id'] = None

        # set to None if image (nullable) is None
        # and model_fields_set contains the field
        if self.image is None and "image" in self.model_fields_set:
            _dict['image'] = None

        # set to None if cluster_size (nullable) is None
        # and model_fields_set contains the field
        if self.cluster_size is None and "cluster_size" in self.model_fields_set:
            _dict['cluster_size'] = None

        # set to None if subpeak (nullable) is None
        # and model_fields_set contains the field
        if self.subpeak is None and "subpeak" in self.model_fields_set:
            _dict['subpeak'] = None

        # set to None if deactivation (nullable) is None
        # and model_fields_set contains the field
        if self.deactivation is None and "deactivation" in self.model_fields_set:
            _dict['deactivation'] = None

        # set to None if order (nullable) is None
        # and model_fields_set contains the field
        if self.order is None and "order" in self.model_fields_set:
            _dict['order'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PointRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "coordinates": obj.get("coordinates"),
            "space": obj.get("space"),
            "kind": obj.get("kind"),
            "label_id": obj.get("label_id"),
            "image": obj.get("image"),
            "values": PointRelationshipsValues.from_dict(obj["values"]) if obj.get("values") is not None else None,
            "x": obj.get("x"),
            "y": obj.get("y"),
            "z": obj.get("z"),
            "entities": [Entity.from_dict(_item) for _item in obj["entities"]] if obj.get("entities") is not None else None,
            "id": obj.get("id"),
            "public": obj.get("public") if obj.get("public") is not None else True,
            "analysis": obj.get("analysis"),
            "cluster_size": obj.get("cluster_size"),
            "subpeak": obj.get("subpeak"),
            "deactivation": obj.get("deactivation"),
            "order": obj.get("order")
        })
        return _obj


