# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class StudyReturnAllOfStudysets(BaseModel):
    """
    StudyReturnAllOfStudysets
    """
    name: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    __properties = ["name", "id", "description"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StudyReturnAllOfStudysets:
        """Create an instance of StudyReturnAllOfStudysets from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if name (nullable) is None
        # and __fields_set__ contains the field
        if self.name is None and "name" in self.__fields_set__:
            _dict['name'] = None

        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StudyReturnAllOfStudysets:
        """Create an instance of StudyReturnAllOfStudysets from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StudyReturnAllOfStudysets.parse_obj(obj)

        _obj = StudyReturnAllOfStudysets.parse_obj({
            "name": obj.get("name"),
            "id": obj.get("id"),
            "description": obj.get("description")
        })
        return _obj

