# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import neurostore_sdk
from neurostore_sdk.model.image_base import ImageBase
from neurostore_sdk import configuration


class TestImageBase(unittest.TestCase):
    """ImageBase unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
