# coding: utf-8

"""
    neurostore api

    Create studysets for meta-analysis

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr, field_validator
from typing import Any, Optional
from typing_extensions import Annotated
from neurostore_sdk.models.studyset_list import StudysetList

from neurostore_sdk.api_client import ApiClient, RequestSerialized
from neurostore_sdk.api_response import ApiResponse
from neurostore_sdk.rest import RESTResponseType


class StudysetsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def studysets_get(
        self,
        search: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="search for entries that contain the substring")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Parameter to sort results on")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="page of results")] = None,
        desc: Annotated[Optional[StrictBool], Field(description="sort results by descending order (as opposed to ascending order)")] = None,
        page_size: Annotated[Optional[Annotated[int, Field(lt=30000, strict=True, ge=1)]], Field(description="number of results to show on a page")] = None,
        paginate: Annotated[Optional[StrictBool], Field(description="whether to paginate results (true) or return all results at once (false)")] = None,
        nested: Annotated[Optional[StrictBool], Field(description="whether to show the URI to a resource (false) or to embed the object in the response (true)")] = None,
        name: Annotated[Optional[StrictStr], Field(description="search the name field for a term")] = None,
        description: Annotated[Optional[StrictStr], Field(description="search description field for a term")] = None,
        source_id: Annotated[Optional[StrictStr], Field(description="id of the resource you are either filtering/copying on")] = None,
        unique: Annotated[Optional[Any], Field(description="whether to list clones with originals")] = None,
        source: Annotated[Optional[StrictStr], Field(description="the source of the resource you would like to filter/copy from")] = None,
        authors: Annotated[Optional[StrictStr], Field(description="search authors")] = None,
        user_id: Annotated[Optional[StrictStr], Field(description="user id you want to filter by")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> StudysetList:
        """GET a list of studysets

        Get a list of studysets.

        :param search: search for entries that contain the substring
        :type search: str
        :param sort: Parameter to sort results on
        :type sort: str
        :param page: page of results
        :type page: int
        :param desc: sort results by descending order (as opposed to ascending order)
        :type desc: bool
        :param page_size: number of results to show on a page
        :type page_size: int
        :param paginate: whether to paginate results (true) or return all results at once (false)
        :type paginate: bool
        :param nested: whether to show the URI to a resource (false) or to embed the object in the response (true)
        :type nested: bool
        :param name: search the name field for a term
        :type name: str
        :param description: search description field for a term
        :type description: str
        :param source_id: id of the resource you are either filtering/copying on
        :type source_id: str
        :param unique: whether to list clones with originals
        :type unique: object
        :param source: the source of the resource you would like to filter/copy from
        :type source: str
        :param authors: search authors
        :type authors: str
        :param user_id: user id you want to filter by
        :type user_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._studysets_get_serialize(
            search=search,
            sort=sort,
            page=page,
            desc=desc,
            page_size=page_size,
            paginate=paginate,
            nested=nested,
            name=name,
            description=description,
            source_id=source_id,
            unique=unique,
            source=source,
            authors=authors,
            user_id=user_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "StudysetList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def studysets_get_with_http_info(
        self,
        search: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="search for entries that contain the substring")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Parameter to sort results on")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="page of results")] = None,
        desc: Annotated[Optional[StrictBool], Field(description="sort results by descending order (as opposed to ascending order)")] = None,
        page_size: Annotated[Optional[Annotated[int, Field(lt=30000, strict=True, ge=1)]], Field(description="number of results to show on a page")] = None,
        paginate: Annotated[Optional[StrictBool], Field(description="whether to paginate results (true) or return all results at once (false)")] = None,
        nested: Annotated[Optional[StrictBool], Field(description="whether to show the URI to a resource (false) or to embed the object in the response (true)")] = None,
        name: Annotated[Optional[StrictStr], Field(description="search the name field for a term")] = None,
        description: Annotated[Optional[StrictStr], Field(description="search description field for a term")] = None,
        source_id: Annotated[Optional[StrictStr], Field(description="id of the resource you are either filtering/copying on")] = None,
        unique: Annotated[Optional[Any], Field(description="whether to list clones with originals")] = None,
        source: Annotated[Optional[StrictStr], Field(description="the source of the resource you would like to filter/copy from")] = None,
        authors: Annotated[Optional[StrictStr], Field(description="search authors")] = None,
        user_id: Annotated[Optional[StrictStr], Field(description="user id you want to filter by")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[StudysetList]:
        """GET a list of studysets

        Get a list of studysets.

        :param search: search for entries that contain the substring
        :type search: str
        :param sort: Parameter to sort results on
        :type sort: str
        :param page: page of results
        :type page: int
        :param desc: sort results by descending order (as opposed to ascending order)
        :type desc: bool
        :param page_size: number of results to show on a page
        :type page_size: int
        :param paginate: whether to paginate results (true) or return all results at once (false)
        :type paginate: bool
        :param nested: whether to show the URI to a resource (false) or to embed the object in the response (true)
        :type nested: bool
        :param name: search the name field for a term
        :type name: str
        :param description: search description field for a term
        :type description: str
        :param source_id: id of the resource you are either filtering/copying on
        :type source_id: str
        :param unique: whether to list clones with originals
        :type unique: object
        :param source: the source of the resource you would like to filter/copy from
        :type source: str
        :param authors: search authors
        :type authors: str
        :param user_id: user id you want to filter by
        :type user_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._studysets_get_serialize(
            search=search,
            sort=sort,
            page=page,
            desc=desc,
            page_size=page_size,
            paginate=paginate,
            nested=nested,
            name=name,
            description=description,
            source_id=source_id,
            unique=unique,
            source=source,
            authors=authors,
            user_id=user_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "StudysetList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def studysets_get_without_preload_content(
        self,
        search: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="search for entries that contain the substring")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Parameter to sort results on")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="page of results")] = None,
        desc: Annotated[Optional[StrictBool], Field(description="sort results by descending order (as opposed to ascending order)")] = None,
        page_size: Annotated[Optional[Annotated[int, Field(lt=30000, strict=True, ge=1)]], Field(description="number of results to show on a page")] = None,
        paginate: Annotated[Optional[StrictBool], Field(description="whether to paginate results (true) or return all results at once (false)")] = None,
        nested: Annotated[Optional[StrictBool], Field(description="whether to show the URI to a resource (false) or to embed the object in the response (true)")] = None,
        name: Annotated[Optional[StrictStr], Field(description="search the name field for a term")] = None,
        description: Annotated[Optional[StrictStr], Field(description="search description field for a term")] = None,
        source_id: Annotated[Optional[StrictStr], Field(description="id of the resource you are either filtering/copying on")] = None,
        unique: Annotated[Optional[Any], Field(description="whether to list clones with originals")] = None,
        source: Annotated[Optional[StrictStr], Field(description="the source of the resource you would like to filter/copy from")] = None,
        authors: Annotated[Optional[StrictStr], Field(description="search authors")] = None,
        user_id: Annotated[Optional[StrictStr], Field(description="user id you want to filter by")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """GET a list of studysets

        Get a list of studysets.

        :param search: search for entries that contain the substring
        :type search: str
        :param sort: Parameter to sort results on
        :type sort: str
        :param page: page of results
        :type page: int
        :param desc: sort results by descending order (as opposed to ascending order)
        :type desc: bool
        :param page_size: number of results to show on a page
        :type page_size: int
        :param paginate: whether to paginate results (true) or return all results at once (false)
        :type paginate: bool
        :param nested: whether to show the URI to a resource (false) or to embed the object in the response (true)
        :type nested: bool
        :param name: search the name field for a term
        :type name: str
        :param description: search description field for a term
        :type description: str
        :param source_id: id of the resource you are either filtering/copying on
        :type source_id: str
        :param unique: whether to list clones with originals
        :type unique: object
        :param source: the source of the resource you would like to filter/copy from
        :type source: str
        :param authors: search authors
        :type authors: str
        :param user_id: user id you want to filter by
        :type user_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._studysets_get_serialize(
            search=search,
            sort=sort,
            page=page,
            desc=desc,
            page_size=page_size,
            paginate=paginate,
            nested=nested,
            name=name,
            description=description,
            source_id=source_id,
            unique=unique,
            source=source,
            authors=authors,
            user_id=user_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "StudysetList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _studysets_get_serialize(
        self,
        search,
        sort,
        page,
        desc,
        page_size,
        paginate,
        nested,
        name,
        description,
        source_id,
        unique,
        source,
        authors,
        user_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if search is not None:
            
            _query_params.append(('search', search))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if desc is not None:
            
            _query_params.append(('desc', desc))
            
        if page_size is not None:
            
            _query_params.append(('page_size', page_size))
            
        if paginate is not None:
            
            _query_params.append(('paginate', paginate))
            
        if nested is not None:
            
            _query_params.append(('nested', nested))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        if description is not None:
            
            _query_params.append(('description', description))
            
        if source_id is not None:
            
            _query_params.append(('source_id', source_id))
            
        if unique is not None:
            
            _query_params.append(('unique', unique))
            
        if source is not None:
            
            _query_params.append(('source', source))
            
        if authors is not None:
            
            _query_params.append(('authors', authors))
            
        if user_id is not None:
            
            _query_params.append(('user_id', user_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'JSON-Web-Token'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/studysets/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


